<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<meta name="viewport" content="width=device-width" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<title>!*type*! !*invoice*! from !*company*!</title>

<style>

* { 
	margin: 0;
	padding: 0;
}

body {
	font-family: !*email_font*!;
	-webkit-font-smoothing: antialiased; 
	-webkit-text-size-adjust: none; 
	width: 100% !important;
	color: !*email_color*!;
}

a {
	color: !*link_color*!;
	text-decoration: none;
}

a:hover {
	color: !*hover_color*!;
}

table.head-wrap, table.body-wrap { width: 100%; }

h1 { font-weight:200; font-size: 44px; }
h2 { font-weight:200; font-size: 37px; }
h3 { font-weight:500; font-size: 27px; }
h4 { font-weight:500; font-size: 23px; }
h5 { font-weight:900; font-size: 17px; }
h6 { font-weight:900; font-size: 14px; }

p { 
	margin-bottom: 10px; 
	font-weight: normal; 
	font-size: 14px; 
	line-height: 1.6;
}

.container {
	max-width: 600px !important;
	margin: 0 auto !important;
}

.content {
	padding: 15px;
	max-width: 600px;
	margin: 0 auto;
	display: block; 
}

.content table { width: 100%; }

.invoice {
	border: 1px solid !*email_color*!;
}

.invoice td {
	border: 1px solid !*email_color*!;
	padding: 7px 14px;
}

</style>

</head>
 
<body bgcolor="#ffffff">

<table class="body-wrap">
	<tr>
		<td></td>
		<td class="container" bgcolor="#ffffff">

			<div class="content">
			<table>
				<tr>
					<td>